<?php

namespace AppBundle\Repository;

/**
 * BookRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
