<?php

namespace AppBundle\Repository;

/**
 * pbooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pbooksRepository extends \Doctrine\ORM\EntityRepository
{
}
